import os
import random

countries = {
  'ALBANIA': 'AL',
  'ARGENTINA': 'AR',
  'AUSTRALIA': 'AU',
  'AUSTRIA': 'AT',
  'BELGIUM': 'BE',
  'BOSNIA AND HERZEGOVINA': 'BA',
  'BRAZIL': 'BR',
  'BULGARIA': 'BG',
  'CANADA': 'CA',
  'CHILE': 'CL',
  'COSTA RICA': 'CR',
  'CROATIA': 'HR',
  'CYPRUS': 'CY',
  'CZECH REPUBLIC': 'CZ',
  'DENMARK': 'DK',
  'ESTONIA': 'EE',
  'FINLAND': 'FI',
  'FRANCE': 'FR',
  'GEORGIA': 'GE',
  'GERMANY': 'DE',
  'GREECE': 'GR',
  'HUNGARY': 'HU',
  'ICELAND': 'IS',
  'INDIA': 'IN',
  'INDONESIA': 'ID',
  'IRELAND': 'IE',
  'ISRAEL': 'IL',
  'ITALY': 'IT',
  'JAPAN': 'JP',
  'LATVIA': 'LV',
  'LUXEMBOURG': 'LU',
  'MALAYSIA': 'MY',
  'MEXICO': 'MX',
  'MOLDOVA': 'MD',
  'NETHERLANDS': 'NL',
  'NEW ZEALAND': 'NZ',
  'NORWAY': 'NO',
  'POLAND': 'PL',
  'PORTUGAL': 'PT',
  'ROMANIA': 'RO',
  'SINGAPORE': 'SG',
  'SLOVAKIA': 'SK',
  'SLOVENIA': 'SI',
  'SOUTH AFRICA': 'ZA',
  'SPAIN': 'ES',
  'SWEDEN': 'SE',
  'SWITZERLAND': 'CH',
  'TURKEY': 'TR',
  'UNITED KINGDOM': 'GB',
  'UNITED STATES': 'US',
}

random_country = random.choice(list(countries.values()))
os.system('nordvpn c ' + random_country)
